services:
  api:
    container_name: api
    build: .
    ports:
      - "6000:8080"
    working_dir: /app
    tty: true
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    extra_hosts:
      - host.docker.internal:host-gateway
