version: "3"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - /cmd/backend
    tty: true
    env_file:
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
