version: "3"
services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - /app
    tty: true
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
