services:
  backend:
    container_name: backend
    build: .
    ports:
      - "6000:8080"
    working_dir: /app
    tty: true
    env_file:
      - ./app/.env
    environment:
      - TZ=Asia/Tokyo
    extra_hosts:
      - host.docker.internal:host-gateway
      - localhost:172.18.0.1
